-- the password hash is generated by BCrypt Calculator Generator(https://www.dailycred.com/article/bcrypt-calculator)

-- INSERT USERS --
INSERT INTO USERS (id, username, password, first_name, last_name, email, enabled, last_password_reset_date) VALUES (1, 'admin', '$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 'Jing', 'Xiao', 'admin@example.com',true, '2017-10-01 18:57:58.508-07');

-- INSERT AUTHORITIES
INSERT INTO AUTHORITY (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (id, name) VALUES (2, 'ROLE_ADMIN');

-- INSERT USER_AUTHORITIES
INSERT INTO USER_AUTHORITY (user_id, authority_id) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (user_id, authority_id) VALUES (1, 2);

-- INSERT CERTIFICATES
-- INSERT INTO CERTIFICAT (id, path, creation, country, state, locality, organizationname, organizationalunitname, commonname, emailadress, datevalidity, valid, valuecertificate) VALUES (1, 'Certficat_par_defaut', CURRENT_DATE , 'France', 'Ile_de_france','Kremlin-Bicêtre', 'CRYPIA','EPITA', 'APPING', 'julien_p@epita.fr', NULL, true, 'MIIDijCCAnKgAwIBAgIJAL2Cr9NmkoNDMA0GCSqGSIb3DQEBCwUAMFoxCzAJBgNVBAYTAmZyMRYwFAYDVQQIDA1pbGUgZGUgZnJhbmNlMRUwEwYDVQQHDAxEZWZhdWx0IENpdHkxHDAaBgNVBAoME0RlZmF1bHQgQ29tcGFueSBMdGQwHhcNMTgwMjE4MTUwNTE2WhcNMjAxMjA4MTUwNTE2WjBaMQswCQYDVQQGEwJmcjEWMBQGA1UECAwNaWxlIGRlIGZyYW5jZTEVMBMGA1UEBwwMRGVmYXVsdCBDaXR5MRwwGgYDVQQKDBNEZWZhdWx0IENvbXBhbnkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn7q2iRWendGHkVLclyJjLw5MDeua3D87YDC0y/HTOOu+Ow+w+KrfJ0j02RTri2nH4xGFnl+aEAdkBJHaIurEgQ3EhXpD6k+msNj9vkeZ0fI22GczrZni9gKEMuAsNWE9yZxwo4LN0xLYjrBJ6u08sDDcTVN6wR5EPt8RcH5IQgurn4mS9cxJyi6AKUXUsOnaQygxO18QHbKjhF8IkoNq90p+vs++X2JlwUonublPtU04mWaZNxI6caw9dniCuLhrg2T9qisOTphrSDJdiElfyNgjZe+ewqlwh7AvQGGy16pjmj9T1RYCgjRjU00PdxXdiXy8N6lcy0ftNMgNhAzdQwIDAQABo1MwUTAdBgNVHQ4EFgQUWbq6JJHkQzwsvM3/cbjhtT/csNMwHwYDVR0jBBgwFoAUWbq6JJHkQzwsvM3/cbjhtT/csNMwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAA5qFppmGk1QXqNHC7sKP6ytiquej9kSUtuujH+QGR+f/0mXMctL7vUiJfcFASyPc5TE71pvNk6r7Ke0unTRNXEg7n7V43xRe1CvsnJvW9aAlANJmd79fRXr+BU2zTBdx4GdgoamfwlBKjHYI04h2542NOps5Wd36O1cpBD/CPkJBksUYjJ3BuIb8tZGGdjtgtwcb9RHV/jkMMYIZhgYrrN+FCkIUgfRdRa1gX+0LzeW2AIfdMCom9l1+X7YO+xWBauDVwhtU05p9tNsdCmTEDYZQeI+ggcHvUSa3KsWAPjoLqZA6/UjUrCnTMejs21Lj1HxZQCFHbpSvfWI8MDw/VA==')
-- INSERT USER_CERTIFICATES


