-- the password hash is generated by BCrypt Calculator Generator(https://www.dailycred.com/article/bcrypt-calculator)

-- INSERT USERS --
INSERT INTO USERS (id, username, password, first_name, last_name, email, enabled, last_password_reset_date) VALUES (1, 'admin', '$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 'Jing', 'Xiao', 'admin@example.com',true, '2017-10-01 18:57:58.508-07');

-- INSERT AUTHORITIES
INSERT INTO AUTHORITY (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (id, name) VALUES (2, 'ROLE_ADMIN');

-- INSERT USER_AUTHORITIES
INSERT INTO USER_AUTHORITY (user_id, authority_id) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (user_id, authority_id) VALUES (1, 2);

-- INSERT CERTIFICATES
INSERT INTO CERTIFICAT (id, path, creation, country, state, locality, organizationname, organizationalunitname, commonname, emailadress, datevalidity, valid) VALUES (1, 'Certficat_par_defaut', CURRENT_DATE , 'France', 'Ile_de_france','Kremlin-Bicêtre', 'CRYPIA','EPITA', 'APPING', 'julien_p@epita.fr', NULL, true)
-- INSERT USER_CERTIFICATES


